# Generated by Django 5.0.1 on 2024-02-11 05:59

import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=utils.image_path.upload_products, verbose_name='Картинка'),
        ),
    ]
