# Generated by Django 5.0.1 on 2024-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
