# Generated by Django 5.0.1 on 2024-02-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_favorite_product_id'),
        ('products', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
